x-common-env: &common-env
  BACKEND_URL: "http://backend:50051"
  DB_USER: "${DB_USER:?error}"
  DB_PASSWORD: "${DB_PASSWORD:?error}"
  DB_HOST: "${DB_HOST:?error}"

services:
  db:
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER:?error}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?error}
      POSTGRES_DB: ${DB_NAME:?error}
    volumes:
      - pgdata:/var/lib/postgresql
    restart: "unless-stopped"

  backend:
    build: ./backend
    ports:
      - 50051:50051

  web-dev:
    profiles: [ "dev" ]
    environment:
      <<: *common-env
      DB_NAME: "xss-app-dev"
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    depends_on:
      - db
      - backend
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./deno.json
        - action: rebuild
          path: ./deno.lock
        - action: rebuild
          path: ./package.json

  web-preview:
    profiles: [ "preview" ]
    environment:
      <<: *common-env
      DB_NAME: "xss-app-preview"
    build:
      context: .
      target: preview
    ports:
      - "4173:4173"

  web:
    profiles: [ "prod" ]
    environment:
      <<: *common-env
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"

volumes:
  pgdata:
