services:
  db:
    image: postgres:18
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER:?error}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?error}
      POSTGRES_DB: ${DB_NAME:?error}
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    build: ./backend
    ports:
      - 50051:50051

  web-dev:
    build:
      context: .
      target: dev
    profiles: ['dev']
    ports:
      - '5173:5173'
    environment:
      HOST: '0.0.0.0'
      PORT: '5173'
      DB_HOST: 'db:5432'
      DB_USER: '${DB_USER:?error}'
      DB_PASSWORD: '${DB_PASSWORD:?error}'
      DB_NAME: '${DB_NAME:?error}'
      BACKEND_URL: 'http://backend:50051'
    depends_on:
      - db
      - backend
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./deno.json
        - action: rebuild
          path: ./deno.lock
        - action: rebuild
          path: ./package.json

  web-preview:
    build:
      context: .
      target: preview
    profiles: ['preview']
    ports:
      - '4173:4173'

  web:
    build:
      context: .
      target: prod
    profiles: ['prod']
    ports:
      - '3000:3000'
    environment:
      HOST: '0.0.0.0'
      PORT: '3000'

volumes:
  pgdata:
