x-common-env: &common-env
  BACKEND_URL: 'http://backend:50051'
  DB_USER: '${DB_USER:?error}'
  DB_PASSWORD: '${DB_PASSWORD:?error}'
  DB_HOST: '${DOCKER_DB_HOST:-db}'

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER:?error}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?error}
      POSTGRES_DB: ${DB_NAME:?error}
    volumes:
      - pgdata:/var/lib/postgresql
    restart: 'unless-stopped'

  backend:
    build: ./backend
    ports:
      - 50051:50051

  web-dev:
    profiles: ['dev']
    environment:
      <<: *common-env
      DB_NAME: 'xss-app-dev'
    build:
      context: .
      target: dev
    ports:
      - '5173:5173'
    depends_on:
      - db
      - backend
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./pnpm-lock.yaml

  web-preview:
    profiles: ['preview']
    environment:
      <<: *common-env
      DB_NAME: 'xss-app-preview'
    build:
      context: .
      target: preview
    ports:
      - '4173:4173'

  web:
    profiles: ['prod']
    environment:
      <<: *common-env
      DB_NAME: 'xss-app'
      BASE_PATH: '/xss-app'
      PORT: '8000'
    build:
      context: .
      target: prod
    ports:
      - '8000:8000'

volumes:
  pgdata:
