services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=file:/app/local.db
    volumes:
      - ./local.db:/app/local.db
      - ./src/lib/server/db/examples:/app/src/lib/server/db/examples:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN:?}
    environment:
      - TUNNEL_TRANSPORT_PROTOCOL=auto

  foo:
    image: alpine:latest
