[project]
name = "simex-debye-grpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "betterproto2-compiler>=0.9.0",
    "betterproto2[all]>=0.9.1",
    "debyecalculator>=1.0.14",
    "grpcio>=1.76.0",
    "grpcio-tools>=1.76.0",
    "numpy>=2.3.5",
    "periodictable>=2.0.2",
    "pydantic>=2.12.5",
    "scipy>=1.16.3",
    "simex-debye",
    "simex-lite",
    "thermo>=0.6.0",
    "torch>=2.9.1",
]

[tool.uv.sources]
simex-debye = { git = "ssh://git@git.xfel.eu:10022/simulation/simex-debye.git" }
simex-lite = { git = "https://github.com/PaNOSC-ViNYL/SimEx-Lite.git" }

[tool.ruff]
exclude = ["src/server/api"]

[tool.hatch.build.targets.wheel]
include = ["src/simex_debye_grpc"]

[tool.hatch.build.targets.wheel.sources]
"src/simex_debye_grpc" = "simex_debye_grpc"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
