syntax = "proto3";

import "files.proto";

service SimulationService {
  rpc CalcDebye(SimulationRequest) returns (SimulationResponse);
  rpc GetSolventInfo(SolventInfoRequest) returns (SolventInfoResponse);
}

message QRange {
  double min = 1;
  double max = 2;
  double step = 3;
}

message Pump {
  double photon_energy_ev = 1;
  double excited_state_energy_ev = 2;
  double excited_state_fraction = 3;
}

message SimulationRequest {
  QRange q_range = 1;
  files.File structure = 2;
}

message SimulationResponse {
  repeated double q = 1;
  repeated double i = 2;
}

message SolventInfoRequest {
  string name = 1;
}

message SolventInfoResponse {
  double rhom = 1;
  double cpm = 2;
}
