# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: simulation.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "SimulationRequest",
    "SimulationRequestPump",
    "SimulationRequestQRange",
    "SimulationRequestSample",
    "SimulationResponse",
    "SimulationServiceBase",
    "SimulationServiceStub",
)

from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpc
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from . import files
from .message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class SimulationRequest(betterproto2.Message):
    q_range: "SimulationRequestQRange" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE
    )

    pump: "SimulationRequestPump" = betterproto2.field(2, betterproto2.TYPE_MESSAGE)

    sample: "SimulationRequestSample" = betterproto2.field(3, betterproto2.TYPE_MESSAGE)


default_message_pool.register_message("", "SimulationRequest", SimulationRequest)


@dataclass(eq=False, repr=False)
class SimulationRequestPump(betterproto2.Message):
    photon_energy_ev: "float" = betterproto2.field(1, betterproto2.TYPE_DOUBLE)

    excited_state_energy_ev: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)

    excited_state_fraction: "float" = betterproto2.field(3, betterproto2.TYPE_DOUBLE)


default_message_pool.register_message(
    "", "SimulationRequest.Pump", SimulationRequestPump
)


@dataclass(eq=False, repr=False)
class SimulationRequestQRange(betterproto2.Message):
    min: "float" = betterproto2.field(1, betterproto2.TYPE_DOUBLE)

    max: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)

    step: "float" = betterproto2.field(3, betterproto2.TYPE_DOUBLE)


default_message_pool.register_message(
    "", "SimulationRequest.QRange", SimulationRequestQRange
)


@dataclass(eq=False, repr=False)
class SimulationRequestSample(betterproto2.Message):
    concentration_solute_molar: "float" = betterproto2.field(
        1, betterproto2.TYPE_DOUBLE
    )

    ground: "files.File" = betterproto2.field(2, betterproto2.TYPE_MESSAGE)

    excited: "files.File" = betterproto2.field(3, betterproto2.TYPE_MESSAGE)

    solvent: "files.File" = betterproto2.field(4, betterproto2.TYPE_MESSAGE)


default_message_pool.register_message(
    "", "SimulationRequest.Sample", SimulationRequestSample
)


@dataclass(eq=False, repr=False)
class SimulationResponse(betterproto2.Message):
    q: "list[float]" = betterproto2.field(1, betterproto2.TYPE_DOUBLE, repeated=True)

    delta_s_total: "list[float]" = betterproto2.field(
        2, betterproto2.TYPE_DOUBLE, repeated=True
    )

    delta_s_solute: "list[float]" = betterproto2.field(
        3, betterproto2.TYPE_DOUBLE, repeated=True
    )

    delta_s_solvent: "list[float]" = betterproto2.field(
        4, betterproto2.TYPE_DOUBLE, repeated=True
    )

    deposited_energy_joule: "float" = betterproto2.field(5, betterproto2.TYPE_DOUBLE)

    delta_temperature_k: "float" = betterproto2.field(6, betterproto2.TYPE_DOUBLE)

    solvent_to_solute_ratio: "float" = betterproto2.field(7, betterproto2.TYPE_DOUBLE)


default_message_pool.register_message("", "SimulationResponse", SimulationResponse)


class SimulationServiceStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def run_simulation(self, message: "SimulationRequest") -> "SimulationResponse":
        return self._channel.unary_unary(
            "/SimulationService/RunSimulation",
            SimulationRequest.SerializeToString,
            SimulationResponse.FromString,
        )(message)


class SimulationServiceBase(betterproto2_grpclib.ServiceBase):
    async def run_simulation(
        self, message: "SimulationRequest"
    ) -> "SimulationResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_run_simulation(
        self, stream: "grpclib.server.Stream[SimulationRequest, SimulationResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.run_simulation(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/SimulationService/RunSimulation": grpclib.const.Handler(
                self.__rpc_run_simulation,
                grpclib.const.Cardinality.UNARY_UNARY,
                SimulationRequest,
                SimulationResponse,
            ),
        }
