# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: files.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "CreateFileRequest",
    "DeleteFileRequest",
    "Empty",
    "File",
    "FileMeta",
    "FileServiceBase",
    "FileServiceStub",
    "FileTypes",
    "GetFileRequest",
    "ListFilesRequest",
    "ListFilesResponse",
    "UpdateFileRequest",
)

from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpc
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from .message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class FileTypes(betterproto2.Enum):
    FILE_TYPE_UNSPECIFIED = 0

    STRUCTURE_FILE = 1

    SOLVENT_FILE = 2


@dataclass(eq=False, repr=False)
class CreateFileRequest(betterproto2.Message):
    type: "FileTypes" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: FileTypes(0)
    )

    filename: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    name: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    contents: "bytes" = betterproto2.field(5, betterproto2.TYPE_BYTES)


default_message_pool.register_message("files", "CreateFileRequest", CreateFileRequest)


@dataclass(eq=False, repr=False)
class DeleteFileRequest(betterproto2.Message):
    type: "FileTypes" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: FileTypes(0)
    )

    id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("files", "DeleteFileRequest", DeleteFileRequest)


@dataclass(eq=False, repr=False)
class Empty(betterproto2.Message):
    pass


default_message_pool.register_message("files", "Empty", Empty)


@dataclass(eq=False, repr=False)
class File(betterproto2.Message):
    type: "FileTypes" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: FileTypes(0)
    )

    id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    filename: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    name: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    contents: "bytes" = betterproto2.field(5, betterproto2.TYPE_BYTES)


default_message_pool.register_message("files", "File", File)


@dataclass(eq=False, repr=False)
class FileMeta(betterproto2.Message):
    id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    filename: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


default_message_pool.register_message("files", "FileMeta", FileMeta)


@dataclass(eq=False, repr=False)
class GetFileRequest(betterproto2.Message):
    type: "FileTypes" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: FileTypes(0)
    )

    id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("files", "GetFileRequest", GetFileRequest)


@dataclass(eq=False, repr=False)
class ListFilesRequest(betterproto2.Message):
    type: "FileTypes" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: FileTypes(0)
    )


default_message_pool.register_message("files", "ListFilesRequest", ListFilesRequest)


@dataclass(eq=False, repr=False)
class ListFilesResponse(betterproto2.Message):
    files: "list[FileMeta]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("files", "ListFilesResponse", ListFilesResponse)


@dataclass(eq=False, repr=False)
class UpdateFileRequest(betterproto2.Message):
    file: "File" = betterproto2.field(1, betterproto2.TYPE_MESSAGE)
    """
    The File resource which replaces the resource on the server.
    """


default_message_pool.register_message("files", "UpdateFileRequest", UpdateFileRequest)


class FileServiceStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def list_files(self, message: "ListFilesRequest") -> "ListFilesResponse":
        return self._channel.unary_unary(
            "/files.FileService/ListFiles",
            ListFilesRequest.SerializeToString,
            ListFilesResponse.FromString,
        )(message)

    def get_file(self, message: "GetFileRequest") -> "File":
        return self._channel.unary_unary(
            "/files.FileService/GetFile",
            GetFileRequest.SerializeToString,
            File.FromString,
        )(message)

    def create_file(self, message: "CreateFileRequest") -> "File":
        return self._channel.unary_unary(
            "/files.FileService/CreateFile",
            CreateFileRequest.SerializeToString,
            File.FromString,
        )(message)

    def update_file(self, message: "UpdateFileRequest") -> "File":
        return self._channel.unary_unary(
            "/files.FileService/UpdateFile",
            UpdateFileRequest.SerializeToString,
            File.FromString,
        )(message)

    def delete_file(self, message: "DeleteFileRequest") -> "Empty":
        return self._channel.unary_unary(
            "/files.FileService/DeleteFile",
            DeleteFileRequest.SerializeToString,
            Empty.FromString,
        )(message)


class FileServiceBase(betterproto2_grpclib.ServiceBase):
    async def list_files(self, message: "ListFilesRequest") -> "ListFilesResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_file(self, message: "GetFileRequest") -> "File":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def create_file(self, message: "CreateFileRequest") -> "File":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_file(self, message: "UpdateFileRequest") -> "File":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_file(self, message: "DeleteFileRequest") -> "Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_list_files(
        self, stream: "grpclib.server.Stream[ListFilesRequest, ListFilesResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.list_files(request)
        await stream.send_message(response)

    async def __rpc_get_file(
        self, stream: "grpclib.server.Stream[GetFileRequest, File]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get_file(request)
        await stream.send_message(response)

    async def __rpc_create_file(
        self, stream: "grpclib.server.Stream[CreateFileRequest, File]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.create_file(request)
        await stream.send_message(response)

    async def __rpc_update_file(
        self, stream: "grpclib.server.Stream[UpdateFileRequest, File]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.update_file(request)
        await stream.send_message(response)

    async def __rpc_delete_file(
        self, stream: "grpclib.server.Stream[DeleteFileRequest, Empty]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.delete_file(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/files.FileService/ListFiles": grpclib.const.Handler(
                self.__rpc_list_files,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListFilesRequest,
                ListFilesResponse,
            ),
            "/files.FileService/GetFile": grpclib.const.Handler(
                self.__rpc_get_file,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetFileRequest,
                File,
            ),
            "/files.FileService/CreateFile": grpclib.const.Handler(
                self.__rpc_create_file,
                grpclib.const.Cardinality.UNARY_UNARY,
                CreateFileRequest,
                File,
            ),
            "/files.FileService/UpdateFile": grpclib.const.Handler(
                self.__rpc_update_file,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateFileRequest,
                File,
            ),
            "/files.FileService/DeleteFile": grpclib.const.Handler(
                self.__rpc_delete_file,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteFileRequest,
                Empty,
            ),
        }
