# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: difference_scattering.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "difference_scattering.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1b\x64ifference_scattering.proto\x12\x18\x64ifference_scattering.v1"4\n\x0eStructureInput\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08xyz_data\x18\x02 \x01(\x0c"1\n\tDsdtTable\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\ntable_data\x18\x02 \x01(\x0c"3\n\x06QRange\x12\x0c\n\x04qmin\x18\x01 \x01(\x01\x12\x0c\n\x04qmax\x18\x02 \x01(\x01\x12\r\n\x05qstep\x18\x03 \x01(\x01"\xa1\x04\n\x1b\x44ifferenceScatteringRequest\x12>\n\x0cground_state\x18\x01 \x01(\x0b\x32(.difference_scattering.v1.StructureInput\x12?\n\rexcited_state\x18\x02 \x01(\x0b\x32(.difference_scattering.v1.StructureInput\x12\x37\n\ndsdt_table\x18\x03 \x01(\x0b\x32#.difference_scattering.v1.DsdtTable\x12\x1e\n\x16\x65xcited_state_fraction\x18\x04 \x01(\x01\x12 \n\x18optical_photon_energy_ev\x18\x05 \x01(\x01\x12\x1f\n\x17\x65xcited_state_energy_ev\x18\x06 \x01(\x01\x12"\n\x1a\x63oncentration_solute_molar\x18\x07 \x01(\x01\x12\x14\n\x0csolvent_name\x18\x08 \x01(\t\x12\x31\n\x07q_range\x18\t \x01(\x0b\x32 .difference_scattering.v1.QRange\x12#\n\x16\x64\x65posited_energy_joule\x18\n \x01(\x01H\x00\x88\x01\x01\x12 \n\x13\x64\x65lta_temperature_k\x18\x0b \x01(\x01H\x01\x88\x01\x01\x42\x19\n\x17_deposited_energy_jouleB\x16\n\x14_delta_temperature_k"\xcf\x01\n\x1c\x44ifferenceScatteringResponse\x12\t\n\x01q\x18\x01 \x03(\x01\x12\x15\n\rdelta_s_total\x18\x02 \x03(\x01\x12\x16\n\x0e\x64\x65lta_s_solute\x18\x03 \x03(\x01\x12\x17\n\x0f\x64\x65lta_s_solvent\x18\x04 \x03(\x01\x12\x1e\n\x16\x64\x65posited_energy_joule\x18\x05 \x01(\x01\x12\x1b\n\x13\x64\x65lta_temperature_k\x18\x06 \x01(\x01\x12\x1f\n\x17solvent_to_solute_ratio\x18\x07 \x01(\x01\x32\xac\x01\n\x1b\x44ifferenceScatteringService\x12\x8c\x01\n\x1b\x43omputeDifferenceScattering\x12\x35.difference_scattering.v1.DifferenceScatteringRequest\x1a\x36.difference_scattering.v1.DifferenceScatteringResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "difference_scattering_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_STRUCTUREINPUT"]._serialized_start = 57
    _globals["_STRUCTUREINPUT"]._serialized_end = 109
    _globals["_DSDTTABLE"]._serialized_start = 111
    _globals["_DSDTTABLE"]._serialized_end = 160
    _globals["_QRANGE"]._serialized_start = 162
    _globals["_QRANGE"]._serialized_end = 213
    _globals["_DIFFERENCESCATTERINGREQUEST"]._serialized_start = 216
    _globals["_DIFFERENCESCATTERINGREQUEST"]._serialized_end = 761
    _globals["_DIFFERENCESCATTERINGRESPONSE"]._serialized_start = 764
    _globals["_DIFFERENCESCATTERINGRESPONSE"]._serialized_end = 971
    _globals["_DIFFERENCESCATTERINGSERVICE"]._serialized_start = 974
    _globals["_DIFFERENCESCATTERINGSERVICE"]._serialized_end = 1146
# @@protoc_insertion_point(module_scope)
