# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import difference_scattering_pb2 as difference__scattering__pb2
import grpc

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    msg = (
        f"The grpc package installed is at version {GRPC_VERSION},"
        " but the generated code in difference_scattering_pb2_grpc.py depends on"
        f" grpcio>={GRPC_GENERATED_VERSION}."
        f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )
    raise RuntimeError(
        msg
    )


class DifferenceScatteringServiceStub:
    """DifferenceScatteringService exposes the Debye difference scattering calculator via gRPC."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeDifferenceScattering = channel.unary_unary(
            "/difference_scattering.v1.DifferenceScatteringService/ComputeDifferenceScattering",
            request_serializer=difference__scattering__pb2.DifferenceScatteringRequest.SerializeToString,
            response_deserializer=difference__scattering__pb2.DifferenceScatteringResponse.FromString,
            _registered_method=True,
        )


class DifferenceScatteringServiceServicer:
    """DifferenceScatteringService exposes the Debye difference scattering calculator via gRPC."""

    def ComputeDifferenceScattering(self, request, context):
        """ComputeDifferenceScattering runs the calculation defined in the example notebook
        and returns the scattering curves for solute, solvent, and total contributions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        msg = "Method not implemented!"
        raise NotImplementedError(msg)


def add_DifferenceScatteringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ComputeDifferenceScattering": grpc.unary_unary_rpc_method_handler(
            servicer.ComputeDifferenceScattering,
            request_deserializer=difference__scattering__pb2.DifferenceScatteringRequest.FromString,
            response_serializer=difference__scattering__pb2.DifferenceScatteringResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "difference_scattering.v1.DifferenceScatteringService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "difference_scattering.v1.DifferenceScatteringService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DifferenceScatteringService:
    """DifferenceScatteringService exposes the Debye difference scattering calculator via gRPC."""

    @staticmethod
    def ComputeDifferenceScattering(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/difference_scattering.v1.DifferenceScatteringService/ComputeDifferenceScattering",
            difference__scattering__pb2.DifferenceScatteringRequest.SerializeToString,
            difference__scattering__pb2.DifferenceScatteringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
